In [109]:
import numpy as np

In [110]:
pts = np.array([[1,3], [2,1], [3, -1], [4, 2]])
pts = np.transpose(pts)
pts

array([[ 1,  2,  3,  4],
       [ 3,  1, -1,  2]])

In [111]:
x = 1

In [112]:
for i in range(len(pts)):
    print(pts[i][1])

2
1


In [113]:

    xj = pts[0]
    yj = pts[1]

    pierwszy_skladnik = yj[0] * (
            ( (x-xj[1]) * (x-xj[2]) * (x-xj[3]) )
            /
            ( (xj[0] - xj[1]) * (xj[0] - xj[2]) * (xj[0] - xj[3]) )
                                 )
    print(pierwszy_skladnik)

3.0


In [114]:
tops = np.array([])
for xindex, xx in enumerate(xj):
    # Create a boolean mask to select all elements except for the one at the specified index
    mask = np.arange(len(xj)) != xindex

    # Use the boolean mask to select the elements we want
    elements_except_current = xj[mask]
    print(elements_except_current)
    top = np.prod(x - elements_except_current)
    print('top is ', top)
    tops = np.append(tops, top)

print(tops)

[2 3 4]
top is  -6
[1 3 4]
top is  0
[1 2 4]
top is  0
[1 2 3]
top is  0
[-6.  0.  0.  0.]


In [116]:
bottoms = np.array([])
for xindex, xx in enumerate(xj):
   print(xindex)
   print(xx)

0
1
1
2
2
3
3
4
