In [73]:
import numpy as np

### Lista zawierająca punkty pomiarowe stanowiące podstawę obliczeń

In [74]:
pts = np.array([[1,3], [2,1], [3, -1], [4, 2]])
pts = np.transpose(pts)
pts

array([[ 1,  2,  3,  4],
       [ 3,  1, -1,  2]])

### Punkt w którym będziemy szukać wartości wielomianu interpolacyjnego

In [75]:
x = 6

### Przypisanie wartości z listy do zmiennych w celu łatwiejszego ich wykorzystania

In [76]:
xj = pts[0]
yj = pts[1]
print('i  = ', np.arange(len(xj)))
print ('Xj = ', xj)
print ('Yj = ', yj)

i  =  [0 1 2 3]
Xj =  [1 2 3 4]
Yj =  [ 3  1 -1  2]


### Obliczanie liczników wszysktich wielomianów i zapisanie ich do tablicy o nazwie tops

In [77]:
tops = np.array([])
for xindex, xx in enumerate(xj):
    # Create a boolean mask to select all elements except for the one at the specified index
    mask = np.arange(len(xj)) != xindex
    # Use the boolean mask to select the elements we want
    elements_except_current = xj[mask]
    top = np.prod(x - elements_except_current)
    tops = np.append(tops, top)

print(tops)

[24. 30. 40. 60.]


### Obliczanie mianowników wszystkich wielomianów i zapisanie ich do tablicy o nazwie bottoms

In [78]:
bottoms = np.array([])
for xindex, xx in enumerate(xj):
   x_other_than_curr = xj[np.arange(len(xj)) != xindex]
   bottom = np.prod(xx - xj[np.arange(len(xj)) != xindex])
   bottoms = np.append(bottoms, bottom)
print(bottoms)

[-6.  2. -2.  6.]


In [79]:
print('tops', tops)
print('bottoms', bottoms)
division = np.divide(tops, bottoms)
poszczegolne_skladniki = (yj*division)
print('poszczegolne_skladniki', poszczegolne_skladniki)
print('suma', np.sum(poszczegolne_skladniki))

tops [24. 30. 40. 60.]
bottoms [-6.  2. -2.  6.]
poszczegolne_skladniki [-12.  15.  20.  20.]
suma 43.0


### Wyświetlenie wartości wielomianu interpolacyjnego w punkcie x

In [80]:
print('Wartość wielomianu interpolacyjnego w punkcie x = ', x, ' wynosi: ', np.sum(poszczegolne_skladniki))

Wartość wielomianu interpolacyjnego w punkcie x =  6  wynosi:  43.0
